name: On create template action

on:
  create

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create a file
        run: echo "Hello, World!" > example.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Test commit
